"""Assemble RUN_SUMMARY.md (settings, materials, mesh, devices, status, numerical tables, file locations, warnings)
from the JSON/CSV outputs of fx_sim.py and fx_post.py.  No physical interpretation."""
import json, glob, os
from pathlib import Path
import numpy as np

HERE = Path(__file__).resolve().parent
DESIGNS = ["final3", "final1", "final0", "final2"]
M = json.load(open(HERE / "materials" / "material_models.json"))
ENV = json.load(open(HERE / "config" / "environment.json"))
PROV = json.load(open(HERE / "config" / "geometry_provenance.json"))
LAM_ZE = M["lambda_ZE_data_nm"]


def jl(p):
    p = HERE / p
    return json.load(open(p)) if p.exists() else None


def fmt(x, n=4):
    return "—" if x is None else (f"{x:.{n}f}" if isinstance(x, (int, float)) else str(x))


def main():
    L = []
    L.append("# RUN_SUMMARY — FDTDX simulations of the four frozen finalists (final3, final1, final0, final2)\n")
    L.append("Simulation/data-generation record only (no physical interpretation). Generated by `make_summary.py`.\n")
    # ---- environment
    L.append("## 1. Environment and execution mode\n")
    L.append(f"* Platform: {ENV['platform']}; CPU: {ENV['cpu'].strip()} ({ENV['n_cores']} cores), RAM {ENV['mem_total_GB']:.1f} GB.")
    L.append(f"* GPU: **none available in this session** (`nvidia-smi` not found, no `/dev/nvidia*`, `torch.cuda.is_available() = False`). JAX devices visible: {ENV['jax']}.")
    L.append("  All runs therefore used the JAX **CPU** backend on a single device; multi-GPU sharding was not applicable (FDTDX's `core/jax/sharding.py` needs ≥ 2 accelerator devices). Measured throughput ≈ 1×10⁷ cell-steps/s (structure runs, dispersive ADE + subpixel tensor), 2.7×10⁷ (empty reference run).")
    L.append(f"* Software: FDTDX {ENV['fdtdx']} from the supplied `fdtdx-main.zip` (SHA256 {ENV['fdtdx_source_sha256'][:16]}…), installed editable in `/opt/venv-fdtdx`; JAX {ENV['jax'].split()[0]}; Python {ENV['python_system']}.\n")
    # ---- geometries
    L.append("## 2. Frozen geometries (`config/geometry_provenance.json`, `config/geometries_four_panel.png`)\n")
    L.append("| design | source file | SHA256 (first 16) | shape | P [nm] | h [nm] | pad | fill |")
    L.append("|---|---|---|---|---|---|---|---|")
    for d in DESIGNS:
        p = PROV[d]
        L.append(f"| {d} | `{p['source_file']}` | {p['sha256'][:16]} | {p['shape'][0]}×{p['shape'][1]} {p['dtype']} | {p['P_nm']:.0f} | {p['h_nm']:.0f} | {p['pad_frac']*100:.0f} % | {p['fill_fraction']:.4f} |")
    L.append("\nCopies: `<design>/rho_hard_binary.npy` (SHA256 of the copies equal the sources). Array convention: rho[i, j], i → x, j → y, 6.445-nm pixels, 1 = a-Si:H.\n")
    # ---- materials
    L.append("## 3. Materials (`materials/material_models.json`, `materials/material_fits.png`, `materials/*_original_vs_fit.csv`)\n")
    it = M["ITO"]; a = M["aSiH"]; g = M["glass"]
    L.append(f"* Source data: the campaign files `ITO_nk.csv`, `aSi_H_measured_Postech.txt`, `SiO2_substrate_measured.txt` read with the campaign loader `materials.py` (same interpolation as TORCWA). λ_ZE from the data: **{LAM_ZE:.3f} nm** (ε′ = 0); fitted model crossing {M['lambda_ZE_fit_nm']:.2f} nm.")
    L.append(f"* ITO (dispersive, ADE): ε∞ = {it['eps_inf']:.4f}, Drude ω_p = {it['wp_rad_s']:.4e} rad/s, γ_D = {it['gamma_d_rad_s']:.3e} rad/s, Lorentz Δε = {it['delta_eps_L']:.4f}, ω₀ = {it['w0_L_rad_s']:.4e} rad/s, γ_L = {it['gamma_L_rad_s']:.3e} rad/s. "
             f"Fit error 1200–1400 nm: max |Δε| = {it['err_max_abs_1200_1400']:.4f} (ε′ {it['err_re_max_1200_1400']:.4f}, ε″ {it['err_im_max_1200_1400']:.4f}), rms {it['err_rms_1200_1400']:.4f}; at λ_ZE: supplied {it['eps_at_lambda_ZE_data'][0]:+.4f}+{it['eps_at_lambda_ZE_data'][1]:.4f}i, fit {it['eps_fit_at_lambda_ZE'][0]:+.4f}+{it['eps_fit_at_lambda_ZE'][1]:.4f}i. (Drude-only reference fit: max |Δε| {it['drude_only_reference']['err_max_abs_1200_1400']:.4f}.)")
    L.append(f"* a-Si:H (dispersive, lossless Lorentz): ε∞ = {a['eps_inf']:.4f}, Δε = {a['delta_eps']:.4f}, ω₀ = {a['w0_rad_s']:.4e} rad/s; max |Δε| = {a['err_max_abs']:.1e} over {a['fit_range_nm'][0]:.0f}–{a['fit_range_nm'][1]:.0f} nm (data end at 1400 nm; the model is used to 1400 nm only through the pulse tail). ε(λ_ZE) = {a['eps_fit_at_lambda_ZE']:.4f} (data {a['eps_at_lambda_ZE_data']:.4f}).")
    L.append(f"* Glass (dispersive, lossless Lorentz): ε∞ = {g['eps_inf']:.4f}, Δε = {g['delta_eps']:.4f}, ω₀ = {g['w0_rad_s']:.4e} rad/s; max |Δε| = {g['err_max_abs']:.1e}; n(λ_ZE) = {np.sqrt(g['eps_fit_at_lambda_ZE']):.5f} (data {g['n_at_lambda_ZE_data']:.5f}).")
    L.append("* Time convention: exp(−iωt) (Drude χ = −ω_p²/(ω² + iγω)); FDTDX phasors accumulate Σ F(t)e^{+iωt}, i.e. the complex amplitudes are in the same convention as TORCWA.\n")
    # ---- settings / mesh
    L.append("## 4. Simulation settings and mesh\n")
    meta = jl("final3/prod/run_meta.json")
    if meta:
        idx = meta["idx"]; ze = np.array(meta["z_edges_m"]) * 1e9; w = np.diff(ze)
        L.append(f"* Unit cell 825 × 825 nm, periodic (Bloch k = 0) in x and y; PML ({meta['pml_cells']} cells) at both z ends; normal incidence from air, E ∥ x, `UniformPlaneSource` (TFSF, one-directional −z), Gaussian pulse centred at 1300 nm with σ_f = 13 THz (σ_t = 12.2 fs, peak at t = 73 fs; amplitude ≥ 0.3 over 1200–1400 nm). Identical source, grid and DFT settings for all structures and for the empty reference run.")
        L.append(f"* Grid: rectilinear. In-plane {meta['nxy']} × {meta['nxy']} cells of {meta['dxy_m']*1e9:.3f} nm (2 × 2 design pixels; the a-Si:H pattern enters through the exact area fill fraction of every cell with FDTDX sub-pixel smoothing = {meta['subpixel_smoothing']}; {100*float(np.mean((np.load(HERE/'final3/rho_hard_binary.npy').reshape(64,2,64,2).mean(axis=(1,3))%1)>0)):.1f} % of the cells are interface cells for final3).")
        L.append(f"  z: {idx['n_z']} cells — glass {ze[idx['z_ito0']]:.0f} nm (PML {w[:meta['pml_cells']].sum():.0f} nm + bulk, 25.8-nm cells, graded to the ITO), ITO **{meta['n_ito']} cells of {meta['dz_ito_m']*1e9:.2f} nm**, a-Si:H graded 4.6 → 12.9 nm then 12.9-nm cells (h exact), air graded to 12.9 nm; source {ze[idx['z_src']]-ze[idx['z_asi1']]:.0f} nm above the a-Si:H top, R plane {ze[idx['z_R']]-ze[idx['z_src']]:.0f} nm above the source (scattered-field region), T plane {ze[idx['z_ito0']]-ze[idx['z_T']]:.0f} nm below the ITO in the glass, air PML {ze[idx['z_pml_top0']]-ze[idx['z_R']]:.0f} nm above the R plane.")
        L.append(f"* Time step {meta['dt_s']*1e18:.2f} as = {meta['courant_factor']} × the exact 3D CFL limit of the rectilinear grid; {meta['n_steps_run']} steps = {meta['time_s']*1e15:.0f} fs (with ITO); no-ITO runs 450 fs. DFT phasors recorded every {meta['dft_stride']} steps ({meta['dft_stride']*meta['dt_s']*1e15:.3f} fs sampling, ≥ 8× the Nyquist rate of the pulse), pulse scaling (no window). Spectra on 1200–1400 nm every 2 nm (101 wavelengths); volume/plane field phasors at λ = {', '.join(f'{l*1e9:.2f}' for l in meta['lam_field_m'])} nm.")
        L.append("* Detectors: `R_plane`, `T_plane` (Ex, Ey, Hx, Hy phasors → ½Re(E×H*)·dA integrated over the cell), `vol_fields` (Ex, Ey, Ez phasors over 4 glass cells + ITO + a-Si:H + 4 air cells), `xz_plane`/`yz_plane` (full height through the cell centre), `probe_asi`/`probe_ito` (time-domain field probes for the decay check). Reference run: same domain filled with air, `T_plane` → incident spectrum P_inc(λ), `R_plane` → TFSF backward leakage (≤ 3×10⁻⁷ of P_inc), `inc_field_plane` → incident Ex phasor for field normalization.")
        L.append("* Quantities: T = −S_z(T plane)/P_inc, R = (S_z(R plane) − leakage)/P_inc, A = 1 − R − T; E/E_inc = phasor / incident Ex phasor (same complex normalization for all structures); F_c = (ω/c) Im ε_ITO(λ) ∫_ITO |E_c/E_inc|² dV / P² (FDTD analogue of the TORCWA ITO loss components); U_c(z) = ∫∫|E_c/E_inc|² dx dy.\n")
    # ---- superseded run
    L.append("* Superseded configuration (kept for the record, not used): a first final3 run with only 350 nm of glass below the ITO gave T < 0 around 1262–1290 nm and A = 1.002 at 1286 nm, because the (±1, 0) diffraction orders are evanescent in the glass only just below their cut-off (n_glass·P = 1251 nm; decay length ≈ 475 nm at λ_ZE, ≈ 1 µm at 1262 nm) and reached the PML. The production mesh uses 1.25 µm of bulk glass + a 412-nm PML. Residual near-cut-off artefacts (1251–1265 nm) are still expected to be larger than elsewhere.\n")
    # ---- status
    L.append("## 5. Run status\n")
    L.append("| run | cells | steps | time [fs] | wall [s] | final max|E| | finite |")
    L.append("|---|---|---|---|---|---|---|")
    for d in ["reference"] + DESIGNS:
        for t in (["ref64"] if d == "reference" else ["prod", "prod_ito10", "noito"]):
            m = jl(f"{d}/{t}/run_meta.json")
            if m:
                L.append(f"| {d}/{t} | {m['n_cells'][0]}×{m['n_cells'][1]}×{m['n_cells'][2]} | {m['n_steps_run']} | {m['time_s']*1e15:.0f} | {m['timing']['run_s']:.0f} | {m.get('max_abs_E_final', float('nan')):.2e} | {m.get('finite', '—')} |")
            elif not (d == "reference" and t != "ref64") and not (t == "prod_ito10" and d != "final3"):
                L.append(f"| {d}/{t} | — | — | — | — | **not run / failed** | — |")
    L.append("")
    # ---- decay
    dec = jl("comparison/decay_check.json")
    if dec:
        L.append("Field decay at the end of each run (time-domain probes, |E| relative to the peak): " + "; ".join(f"{k}: a-Si {v['probe_asi_end_over_peak']:.1e}, ITO {v['probe_ito_end_over_peak']:.1e}" for k, v in dec.items()) + ".\n")
    # ---- spectra table
    L.append("## 6. Numerical tables\n")
    st = jl("comparison/spectra_table.json")
    if st:
        L.append("### 6.1 R, T, A at λ_ZE and extrema (FDTDX)\n")
        L.append("| run | R(λ_ZE) | T(λ_ZE) | A(λ_ZE) | λ(A max) [nm] | A max | λ(T min) | T min | λ(R max) | R max |")
        L.append("|---|---|---|---|---|---|---|---|---|---|")
        for k, v in st.items():
            L.append(f"| {k} | {v['R_ZE']:.4f} | {v['T_ZE']:.4f} | {v['A_ZE']:.4f} | {v['lam_Amax']:.0f} | {v['A_max']:.4f} | {v['lam_Tmin']:.0f} | {v['T_min']:.4f} | {v['lam_Rmax']:.0f} | {v['R_max']:.4f} |")
        L.append("")
    # ---- comparison with TORCWA
    L.append("### 6.2 TORCWA (certified, [11,11]) vs FDTDX at λ_ZE\n")
    L.append("| design | R TORCWA | R FDTDX | T TORCWA | T FDTDX | A TORCWA | A FDTDX | F_z TORCWA | F_z FDTDX | F_tot TORCWA | F_tot FDTDX | ⟨\\|E_z/E_inc\\|²⟩ ITO TORCWA / FDTDX | max TORCWA / FDTDX |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for d in DESIGNS:
        tr = PROV[d]["torcwa_reference"]; fd = jl(f"{d}/prod/field_diagnostics.json"); sp = st.get(f"{d}/prod") if st else None
        key = f"{LAM_ZE:.3f}"
        if fd and sp and key in fd:
            f = fd[key]
            L.append(f"| {d} | {tr['R_certified']:.4f} | {sp['R_ZE']:.4f} | {tr['T_certified']:.4f} | {sp['T_ZE']:.4f} | {tr['A_certified']:.4f} | {sp['A_ZE']:.4f} | {tr['Fz_certified']:.4f} | {f['Fz']:.4f} | {tr['Ftot_certified']:.4f} | {f['Ftot']:.4f} | {tr['mean_Ez2']:.2f} / {f['mean_Ez2_ito_mid']:.2f} | {tr['max_Ez2']:.1f} / {f['max_Ez2_ito_mid']:.1f} |")
        else:
            L.append(f"| {d} | {tr['R_certified']:.4f} | — | {tr['T_certified']:.4f} | — | {tr['A_certified']:.4f} | — | {tr['Fz_certified']:.4f} | — | {tr['Ftot_certified']:.4f} | — | {tr['mean_Ez2']:.2f} / — | {tr['max_Ez2']:.1f} / — |")
    L.append("\nF_c(FDTDX) is the volume-loss integral over the ITO cells with the fitted ε_ITO(λ); TORCWA values are the Phase-1 certification numbers (F from the Fourier–Parseval route). FDTDX A comes from the flux planes; F_tot − A is a consistency residual (all other media are lossless).\n")
    # ---- multipoles
    L.append("### 6.3 Multipole diagnostics of the a-Si:H polarization current (FDTDX, vacuum long-wavelength Cartesian forms; p_eff = p + ikT)\n")
    L.append("| run | λ [nm] | ED_eff | MD | EQ | MQ | TD diag / sum | ED(p only) / sum | P_sum [W per (V/m)²] |")
    L.append("|---|---|---|---|---|---|---|---|---|")
    for d in DESIGNS:
        for t in ("prod", "noito"):
            fd = jl(f"{d}/{t}/field_diagnostics.json")
            if not fd:
                continue
            keys = [k for k in fd if not k.startswith("_")]
            show = [f"{LAM_ZE:.3f}"] + ([f"{fd['_lam_field_nearest_to_Amax']:.3f}"] if "_lam_field_nearest_to_Amax" in fd and abs(fd["_lam_field_nearest_to_Amax"] - LAM_ZE) > 0.5 else [])
            for k in show:
                if k in fd:
                    mp = fd[k]["multipoles"]
                    L.append(f"| {d}/{t} | {fd[k]['lambda_nm']:.2f} | {mp['frac_ED_eff']:.3f} | {mp['frac_MD']:.3f} | {mp['frac_EQ']:.3f} | {mp['frac_MQ']:.3f} | {mp['TD_diag_over_sum']:.3f} | {mp['ED_p_only_over_sum']:.3f} | {mp['P_sum_eff_W']:.3e} |")
    L.append("\nTORCWA Stage-5 cross-check values (final3: ED ≈ 56 %, MD ≈ 16 %, EQ ≈ 28 %, TD diagnostic ≈ 11 %; final0: 45 / 15 / 39 / 14 %). Raw complex moments p, m, T, Qe, Qm and all powers: `<design>/<tag>/field_diagnostics.json` (key = wavelength).\n")
    # ---- mesh convergence
    cv = jl("comparison/mesh_convergence_final3.json")
    if cv:
        L.append("### 6.4 Mesh check (final3, ITO z-refinement at fixed in-plane grid)\n")
        L.append(f"* Mesh A: {cv['mesh_A']['n_ito']} ITO cells ({cv['mesh_A']['dz_ito_nm']:.2f} nm), dt {cv['mesh_A']['dt_as']:.2f} as, {cv['mesh_A']['steps']} steps. Mesh B: {cv['mesh_B']['n_ito']} ITO cells ({cv['mesh_B']['dz_ito_nm']:.2f} nm), dt {cv['mesh_B']['dt_as']:.2f} as, {cv['mesh_B']['steps']} steps.")
        L.append(f"* max |ΔR| = {cv['max_abs_dR']:.4f}, max |ΔT| = {cv['max_abs_dT']:.4f}, max |ΔA| = {cv['max_abs_dA']:.4f} over 1200–1400 nm; at λ_ZE: R {cv['R_ZE'][0]:.4f} → {cv['R_ZE'][1]:.4f}, T {cv['T_ZE'][0]:.4f} → {cv['T_ZE'][1]:.4f}, A {cv['A_ZE'][0]:.4f} → {cv['A_ZE'][1]:.4f}; λ(A max) {cv['lam_Amax'][0]:.0f} → {cv['lam_Amax'][1]:.0f} nm.")
        if "Fz" in cv:
            L.append(f"* F_z {cv['Fz'][0]:.4f} → {cv['Fz'][1]:.4f}; F_tot {cv['Ftot'][0]:.4f} → {cv['Ftot'][1]:.4f}; ⟨|E_z/E_inc|²⟩ ITO mid-plane {cv['mean_Ez2_ito_mid'][0]:.2f} → {cv['mean_Ez2_ito_mid'][1]:.2f}; max {cv['max_Ez2_ito_mid'][0]:.1f} → {cv['max_Ez2_ito_mid'][1]:.1f}; multipole fractions A {cv['multipole_fracs_A']} / B {cv['multipole_fracs_B']}.")
        L.append("* The production grid (mesh A) was used for final1, final0 and final2.\n")
    # ---- files
    L.append("## 7. File locations\n")
    L.append("""* `config/`: `environment.json`, `geometry_provenance.json`, `geometries_four_panel.png`.
* `materials/`: `material_models.json`, `ITO_eps_original_vs_fit.csv`, `aSiH_glass_eps_original_vs_fit.csv`, `material_fits.png`.
* `<design>/rho_hard_binary.npy`; `<design>/prod/` (with ITO) and `<design>/noito/` (ITO removed, same a-Si:H geometry, same grid):
  `run_meta.json` (exact settings: grid edges, dt, steps, indices, wavelengths), `spectra_<tag>.csv/.npz/.png`, `fields_normalized.npz`
  (complex E/E_inc [λ, c, x, y, z] over glass/ITO/a-Si:H/air block + xz/yz full-height planes), `fields_<λ>nm.png` (|Ex|², |Ey|², |Ez|², |E|² in the
  ITO mid-plane xy, central xz and yz), `Uz_<λ>nm.csv/.npz` (Ux, Uy, Uz, Utot vs z, native cells and 10-nm resampling), `Ez2_slices_aSi_<λ>nm.npz`
  (|Ez/E_inc|² on every a-Si:H z cell), `field_diagnostics.json` (R/T/A-related ITO loss F_x/F_y/F_z/F_tot, |Ez|² statistics, raw multipole moments
  and powers per wavelength), `Jz_ITO_<λ>nm.npz` (ITO polarization current density at the mid-plane, with ITO only), `compare_with_without_ITO.png`.
  Raw phasor dumps `phasors.npz` (all detectors, unnormalized) are kept in the working directory but excluded from git (size).
* `final3/prod_ito10/`: the finer-ITO mesh run (10 cells of 2.3 nm).  `final3/prod_glass350nm_superseded/`, `reference/ref64_glass350nm_superseded/`: the superseded thin-glass configuration.
* `reference/ref64/`: empty-domain reference (incident spectrum, leakage, incident field phasor).
* `comparison/`: `spectra_table.csv/.json`, `overlay_A_withITO.png`, `overlay_RT_withITO.png`, `overlay_R_noITO.png`, `overlay_RT_noITO.png`,
  `overlay_Uz_Utot_vs_z_over_h.png`, `overlay_ITO_plane_Ez2_common_scale.png`, `mesh_convergence_final3.json/.png`, `decay_check.json`, `deliverable_check.json`.
* `logs/`: per-run logs; `queue_A.sh`, `queue_B.sh`: the exact command lines.
""")
    # ---- warnings
    L.append("## 8. Warnings, limitations, failed items\n")
    warn = jl("comparison/warnings.json") or []
    base = [
        "No GPU in the session: CPU-only execution forced a coarser production grid (64 cells per period, 12.9-nm cells with sub-pixel smoothing, 5 ITO cells) than a GPU run would use; the ITO z-refinement check quantifies the mesh sensitivity, the in-plane resolution was not varied.",
        "Near the glass Rayleigh cut-off (1251 nm) the (±1,0) orders are grazing/evanescent with decay lengths up to microns; values within ~1251–1265 nm carry a larger PML-related uncertainty (see §4).",
        "Multipole moments use the vacuum long-wavelength Cartesian formulas with the origin at the a-Si:H centre; the a-Si:H sits on ITO/glass in a periodic lattice, so the 'radiated power' weights are diagnostics only. Partial interface cells are weighted by their exact fill fraction.",
        "The 'main resonance' field maps use the recorded field wavelength closest to the A-maximum of the spectrum (recorded set 1294/1298/1302.28/1306/1310 nm with ITO; 1280–1320 nm every 10 nm without ITO); the mismatch is stated in `field_diagnostics.json` (`_mismatch_nm`).",
        "Without ITO all media are lossless: A_noITO is a numerical residual (flux-plane closure), reported as such.",
    ]
    for w_ in base + warn:
        L.append(f"* {w_}")
    (HERE / "RUN_SUMMARY.md").write_text("\n".join(L) + "\n")
    print("RUN_SUMMARY.md written", len(L), "lines")


if __name__ == "__main__":
    main()
