"""Assemble the machine-readable tables of the campaign into outputs/REPORT_TABLES.md
and outputs/results.csv|json (Stage 1-3 runs + certified finalists), and copy the
best certified design to outputs/best/."""

import csv
import json
import shutil
from pathlib import Path

import numpy as np

import config
import plots

OUT = config.OUT


def load(p):
    return json.load(open(p)) if Path(p).exists() else None


def main():
    L = ["# Campaign tables (generated by report_tables.py)", ""]
    allrows = []
    for st in ("stage1", "stage2", "stage3", "stage1c", "stage2c"):
        rows = load(OUT / st / "results.json")
        if not rows:
            continue
        allrows += rows
        L += [f"## {st}: top 12 runs by hard-binary F_z (optimizer order)", "",
              "| tag | P | h | pad | seed | order | iters | warm | F_z soft | F_z hard | F_x | F_y | F_tot | A | resid | eta_z | fill | S_flip lr/ud | wall s |",
              "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
        for r in rows[:12]:
            L.append(f"| {r['tag']} | {r['P']:.0f} | {r['h']:.0f} | {r['pad_frac']:.2f} | {r['seed']} | {r['order']} | {r['n_iter']} | {'y' if r.get('warm_from') else 'n'} | "
                     f"{r['Fz_soft']:.4f} | {r['Fz_hard']:.4f} | {r['Fx_hard']:.4f} | {r['Fy_hard']:.4f} | {r['Ftot_hard']:.4f} | {r['A_hard']:.4f} | {r['identity_resid_hard']:+.1e} | "
                     f"{r['eta_z_hard']:.3f} | {r['fill']:.3f} | {r['s_flip_lr']:.2f}/{r['s_flip_ud']:.2f} | {r['wall_s']:.0f} |")
        L.append("")
        if st == "stage1":
            Ps = sorted(set(r["P"] for r in rows)); hs = sorted(set(r["h"] for r in rows)); pads = sorted(set(r["pad_frac"] for r in rows))
            L += ["### Stage 1 landscape: best-of-seeds hard F_z per (P, h), best over pad", "", "| h \\ P | " + " | ".join(f"{P:.0f}" for P in Ps) + " |", "|---|" + "---|" * len(Ps)]
            for h in hs:
                L.append(f"| {h:.0f} | " + " | ".join((lambda v: f"{max(v):.3f}" if v else "-")([r["Fz_hard"] for r in rows if r["P"] == P and r["h"] == h]) for P in Ps) + " |")
            L += ["", "### Stage 1: pad effect (best hard F_z over P, h, seeds)", "", "| pad | best F_z | mean F_z |", "|---|---|---|"]
            for p in pads:
                v = [r["Fz_hard"] for r in rows if r["pad_frac"] == p]
                L.append(f"| {p:.2f} | {max(v):.4f} | {np.mean(v):.4f} |")
            L += ["", "### Stage 1: seed spread per (P, h, pad) cell (max - min of hard F_z over the 3 seeds)", ""]
            spreads = []
            for P in Ps:
                for h in hs:
                    for p in pads:
                        v = [r["Fz_hard"] for r in rows if r["P"] == P and r["h"] == h and r["pad_frac"] == p]
                        if len(v) > 1:
                            spreads.append((max(v) - min(v), max(v), P, h, p))
            if spreads:
                spreads.sort(reverse=True)
                L.append(f"- median spread {np.median([s[0] for s in spreads]):.4f}, max spread {spreads[0][0]:.4f} at P={spreads[0][2]:.0f} h={spreads[0][3]:.0f} pad={spreads[0][4]:.2f} (best {spreads[0][1]:.4f}); "
                         f"median relative spread {np.median([s[0]/max(s[1],1e-9) for s in spreads]):.3f}")
            L.append("")
            try:
                plots.landscape_plot(rows, OUT / "stage1" / "landscape.png")
            except Exception as e:
                L.append(f"(landscape plot failed: {e})")
    if allrows:
        keys = list(allrows[0].keys())
        with open(OUT / "results.csv", "w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=keys, extrasaction="ignore"); w.writeheader(); w.writerows(allrows)
        with open(OUT / "results.json", "w") as fh:
            json.dump(allrows, fh, indent=1)
    cert = load(OUT / "stage4" / "certification.json")
    if cert:
        L += ["## Stage 4: certified finalists (see outputs/stage4/CERTIFICATION.md for the full tables)", ""]
        L += (OUT / "stage4" / "CERTIFICATION.md").read_text().split("\n", 1)[1].splitlines()
        best = cert[0]
        b = OUT / "best"; b.mkdir(exist_ok=True)
        src = OUT / "stage4" / best["tag"]
        for f in ("rho_hard_binary.npy", "geometry.png", "loss_maps.png", "history.png", "certify.json", "fields_ito_order9.npz"):
            if (src / f).exists():
                shutil.copy(src / f, b / f)
        shutil.copy(Path(best["run_dir"]) / "result.json", b / "result.json")
        shutil.copy(Path(best["run_dir"]) / "design_mask.npy", b / "design_mask.npy")
        s5 = OUT / "stage5" / best["tag"]
        if s5.exists():
            for f in ("spectra.png", "detuning_map.png", "loss_scaling.png", "poles.json", "physics.json", "spectra.npz", "detuning.npz", "multipoles.json"):
                if (s5 / f).exists():
                    shutil.copy(s5 / f, b / f)
        L += ["", f"Best certified design: **{best['tag']}** -> outputs/best/", ""]
    phys = OUT / "stage5" / "PHYSICS.md"
    if phys.exists():
        L += ["## Stage 5: physics (see outputs/stage5/PHYSICS.md)", ""] + phys.read_text().split("\n", 1)[1].splitlines()
    (OUT / "REPORT_TABLES.md").write_text("\n".join(L) + "\n")
    print(f"wrote {OUT/'REPORT_TABLES.md'} ({len(allrows)} runs)")


if __name__ == "__main__":
    main()
