"""Generate VALIDATION_SUMMARY.md (tables of provenance, convergence/artefact checks, TORCWA <-> FDTDX comparison
and field-enhancement comparison for every candidate that has outputs) from the stored JSON files only."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def f(x, fmt="{:.3f}"):
    try:
        return "-" if x is None else fmt.format(x)
    except Exception:
        return str(x)


def main():
    man = json.load(open(HERE / "manifest.json")); mats = json.load(open(HERE / "materials_fit_check.json"))
    L = ["# VALIDATION_SUMMARY — independent FDTDX validation of the frozen activation finalists", "",
         "Generated by `fx_summary.py` from `manifest.json`, `<tag>/spectra/checks_<tag>.json`, `<tag>/spectra/crosscheck_<tag>.json`",
         "and `<tag>/raw_fields/prod/run_meta.json`.  Method: `METHOD.md`; layout: `README.md`.  Nothing here changed any geometry.", "",
         "## 1. Frozen structures (exact binaries used by FDTDX; SHA256 of the uint8 array)", "",
         "| candidate | role | source rho | sha256 (uint8) | P [nm] | h [nm] | d_ITO [nm] | pad | fill | field lambdas [nm] | pol / incidence |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    for tag, c in man["candidates"].items():
        L.append(f"| {tag} | {c['role']} | `{Path(c['source_rho']).name if not c['source_rho'].startswith('generated') else c['source_rho']}` | {c['sha256_uint8_array'][:16]} | {c['P_nm']:.1f} | {c['h_nm']:.1f} | {c['d_ito_nm']:.0f} | {c['pad_frac']*100:.0f} % | {c['fill_fraction']:.3f} | {', '.join(f'{x:.1f}' for x in c['field_lams_nm'])} | x-pol, normal, from air |")
    e = mats["errors"]
    L += ["", f"Materials: the four-finalists ADE fits of the supplied files; ITO fit errors over 1252-1400 nm: max |d eps'| = {e['1252-1400']['max_err_eps1']:.4f} (rms {e['1252-1400']['rms_err_eps1']:.4f}), "
          f"max |d eps''| = {e['1252-1400']['max_err_eps2']:.4f} (rms {e['1252-1400']['rms_err_eps2']:.4f}); over 1290-1320 nm: {e['1290-1320']['max_err_eps1']:.4f} / {e['1290-1320']['max_err_eps2']:.4f}; "
          f"fitted ENZ crossing {mats['errors']['lambda_ENZ_fit_nm']:.2f} nm vs 1302.28 nm supplied.  a-Si:H and glass fits: |d eps| <= 3.3e-5 / 2.1e-5 (lossless Lorentz).", "",
          "## 2. Runs, convergence and artefact checks", "",
          "| candidate | cells | steps | time [fs] | dt [as] | wall [s] | final max\\|E\\| | probe decay a-Si / ITO | early 300 fs vs full: max dT | early 450 fs vs full: max dT | R_max | T_min | A_min | leak/P_inc | ITO thickness [nm] |",
          "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    rows = {}
    for tag in man["candidates"]:
        cp = HERE / tag / "spectra" / f"checks_{tag}.json"; mp = HERE / tag / "raw_fields" / "prod" / "run_meta.json"
        if not cp.exists():
            L.append(f"| {tag} | (not run) | | | | | | | | | | | | | |"); continue
        c = json.load(open(cp)); m = json.load(open(mp)); rows[tag] = c
        ew = c.get("early_window_convergence", {}); d = c.get("decay_probes", {})
        L.append(f"| {tag} | {'x'.join(str(x) for x in m['n_cells'])} | {m['n_steps_run']} | {m['time_s']*1e15:.0f} | {m['dt_s']*1e18:.2f} | {m['timing'].get('run_s', 0):.0f} | {m['max_abs_E_final']:.1e} | "
                 f"{f(d.get('probe_asi', {}).get('end_over_peak'), '{:.1e}')} / {f(d.get('probe_ito', {}).get('end_over_peak'), '{:.1e}')} | {f(ew.get('_early', {}).get('max_abs_dT_vs_full'), '{:.4f}')} | {f(ew.get('_early2', {}).get('max_abs_dT_vs_full'), '{:.4f}')} | "
                 f"{c['R_max']:.3f} | {c['T_min']:.3f} | {c['A_min']:.3f} | {c['leak_over_Pinc_max']:.1e} | {c['ito_layer_check']['thickness_nm']:.2f} |")
    L += ["", "## 3. TORCWA ([9,9], tabulated materials) vs FDTDX: spectra", "",
          "| candidate | lam(T_min) TORCWA / FDTDX [nm] | T_min TORCWA / FDTDX | A_max TORCWA / FDTDX | best shift d [nm] (TORCWA(lam+d) = FDTDX(lam)) | rms dT no shift / after shift | max dT / dR / dA after shift | shift explained by material fits [nm] |",
          "|---|---|---|---|---|---|---|---|"]
    for tag in rows:
        xp = HERE / tag / "spectra" / f"crosscheck_{tag}.json"
        if not xp.exists():
            L.append(f"| {tag} | (crosscheck not run) | | | | | | |"); continue
        x = json.load(open(xp)); mf = x["material_fit_isolation"]
        L.append(f"| {tag} | {x['lam_T_min']['torcwa']:.1f} / {x['lam_T_min']['fdtdx']:.1f} | {x['T_min']['torcwa']:.3f} / {x['T_min']['fdtdx']:.3f} | {x['A_max']['torcwa']:.3f} / {x['A_max']['fdtdx']:.3f} | {x['best_shift_nm']:+.2f} | "
                 f"{x['rms_dT_no_shift']:.4f} / {x['rms_dT_after_shift']:.4f} | {x['max_dT_after_shift']:.3f} / {x['max_dR_after_shift']:.3f} / {x['max_dA_after_shift']:.3f} | {mf['shift_from_material_fits_nm']:+.1f} |")
    L += ["", "## 4. ITO field enhancement and loss: FDTDX at lambda vs TORCWA at the same lambda and at the shift-equivalent lambda + d", "",
          "| candidate | lambda [nm] | <\\|Ez/E_inc\\|^2>_ITO FDTDX | TORCWA same lambda | TORCWA lambda + d | F_z FDTDX / TORCWA(lambda + d) | F_tot FDTDX / TORCWA(lambda + d) | A flux FDTDX / TORCWA(lambda + d) |",
          "|---|---|---|---|---|---|---|---|"]
    for tag in rows:
        xp = HERE / tag / "spectra" / f"crosscheck_{tag}.json"
        if not xp.exists():
            continue
        x = json.load(open(xp))
        for k, v in x["fields_vs_torcwa"].items():
            L.append(f"| {tag} | {float(k):.1f} | {v['fdtdx']['mean_Ez2']:.2f} | {v['torcwa_same_lambda']['mean_Ez2']:.2f} | {v['torcwa_shift_equivalent']['mean_Ez2']:.2f} ({v['torcwa_shift_equivalent']['lam']:.1f} nm) | "
                     f"{v['fdtdx']['Fz']:.3f} / {v['torcwa_shift_equivalent']['Fz']:.3f} | {v['fdtdx']['Ftot']:.3f} / {v['torcwa_shift_equivalent']['Ftot']:.3f} | {v['fdtdx']['A_flux']:.3f} / {v['torcwa_shift_equivalent']['A']:.3f} |")
    L += ["", "## 5. Files behind every figure", ""]
    for tag in rows:
        pm = HERE / tag / "metadata" / "plot_manifest.json"
        if pm.exists():
            p = json.load(open(pm)); pr = p["provenance"]
            L.append(f"* **{tag}**: raw `{Path(pr['raw_phasors']).relative_to(HERE)}` (sha256 {pr['raw_sha256'][:16]}), reference `{Path(pr['reference_phasors']).relative_to(HERE)}`, geometry sha256 {pr['geometry_sha256_uint8'][:16]}; "
                     f"normalized fields `{Path(p['raw_normalized']).relative_to(HERE)}`; volume block z = {pr['boundaries_nm']['volume_block'][0]:.0f}-{pr['boundaries_nm']['volume_block'][1]:.0f} nm "
                     f"(ITO {pr['boundaries_nm']['ITO_bottom']:.1f}-{pr['boundaries_nm']['ITO_top']:.1f} nm, a-Si:H top {pr['boundaries_nm']['aSiH_top']:.1f} nm); figures: spectra, zprofile, {len(p['figures']['xy_slices'])} xy-slice panels, {len(p['figures']['xz_yz'])} xz/yz cuts; "
                     f"colour scales: {p['colour_scales']['xy_slices']}.")
    (HERE / "VALIDATION_SUMMARY.md").write_text("\n".join(L) + "\n"); print("VALIDATION_SUMMARY.md written for", list(rows))


if __name__ == "__main__":
    main()
