"""Collect the sanity-check numbers of the study into outputs/SUMMARY.md (read from the json outputs, nothing recomputed)."""
import json
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
OUT = HERE / "outputs"


def main(prefix="fig3"):
    em = json.load(open(OUT / "em_checks.json"))
    fit = json.load(open(OUT / "ito_te_models.json"))
    fb = json.load(open(OUT / f"{prefix}_feedback_summary.json"))
    fam = np.load(OUT / "final3_Te_family_fdtdx.npz")
    L = []
    L.append("# Numbers (generated by make_summary.py)\n")
    # 1. eps fits
    L.append("## 1. Per-Te ITO fits vs the ZIP target eps_meas + delta-Drude(Te)\n")
    L.append("| Te [K] | max abs err 1230-1280 | rms 1230-1280 | max abs err 1200-1400 | eps_target(1255) | eps_fit(1255) |")
    L.append("|---|---|---|---|---|---|")
    for k, v in fit["fit_check"].items():
        if k.startswith("check"):
            continue
        L.append(f"| {v['Te_K']:.0f} | {v['band_1230_1280']['max_abs']:.4f} | {v['band_1230_1280']['rms']:.4f} | {v['band_1200_1400']['max_abs']:.4f} | "
                 f"{v['eps_target_1255'][0]:+.4f}{v['eps_target_1255'][1]:+.4f}i | {v['eps_model_1255'][0]:+.4f}{v['eps_model_1255'][1]:+.4f}i |")
    c = fit["fit_check"]["check_300K"]
    L.append(f"\n300 K limit: |target(300 K) − measured| = {c['max_abs_target300_minus_measured']:.1e} (exact); "
             f"|fit(300 K) − measured| ≤ {c['max_abs_fit300_minus_measured_1230_1280']:.4f} in 1230-1280 nm "
             f"(existing cold model: ≤ {c['max_abs_coldmodel_minus_measured_1230_1280']:.4f}); "
             f"|fit(300 K) − existing cold model| ≤ {c['max_abs_fit300_minus_coldmodel_1230_1280']:.4f} (1230-1280) / {c['max_abs_fit300_minus_coldmodel_1200_1400']:.4f} (1200-1400).\n")
    # 2. EM runs
    L.append("## 2. FDTDX runs (600 fs): decay, closure, A_ITO checks\n")
    L.append("| Te [K] | probe end/peak a-Si / ITO | T range in band | A_ITO range in band | max abs(A_ITO − (1−R−T)) band / outside 1250-1265 | 1255 nm: 1−R−T / A_ITO / volume loss | 1275 nm: 1−R−T / A_ITO / volume loss | non-ITO loss / A |")
    L.append("|---|---|---|---|---|---|---|---|")
    for k, r in em["runs"].items():
        cl = r["closure"]; l1, l2 = r["ito_loss_check"]
        L.append(f"| {k} | {r['decay']['probe_asi_end_over_peak']:.1e} / {r['decay']['probe_ito_end_over_peak']:.1e} | {cl['min_T_band']:+.3f} … {max(cl.get('max_T_band', 0), 0):.3f} | "
                 f"{cl['min_A_ito_band']:.3f} … {cl['max_A_ito_band']:.3f} | {cl['A_ito_minus_A_rt']['max_abs_band']:.3f} / {cl['A_ito_minus_A_rt']['max_abs_band_outside_1250_1265']:.3f} | "
                 f"{l1['A_rt_from_flux']:.3f} / {l1['A_ito_from_flux_planes']:.3f} / {l1['F_ito']:.3f} | {l2['A_rt_from_flux']:.3f} / {l2['A_ito_from_flux_planes']:.3f} / {l2['F_ito']:.3f} | {max(l1['nonITO_over_A'], l2['nonITO_over_A']):.1e} |")
    L.append("\nT range column: min T in band (negative values = closure/truncation error) … max T in band.  "
             "Non-ITO loss: a-Si:H + glass volume-loss integrals (lossless Lorentz models, ADE damping floor 1e9 rad/s) relative to A_ITO.  "
             f"TFSF backward leakage ≤ {max(r['closure']['max_leak_over_Pinc'] for r in em['runs'].values()):.1e} of P_inc.\n")
    # 3. window / pole checks
    L.append("## 3. Time-window convergence and the 300 K cross-checks\n")
    ex = em.get("extras", {})
    for tag, e in ex.items():
        L.append(f"* **{e['label']}** — decay a-Si {e['decay']['probe_asi_end_over_peak']:.1e} / ITO {e['decay']['probe_ito_end_over_peak']:.1e}; "
                 + "; ".join(f"{q}: max|Δ| {e[q]['max_abs_band']:.4f} in band (1250-1265: {e[q]['max_abs_1250_1265']:.4f}, outside: {e[q]['max_abs_band_outside_1250_1265']:.4f}), rms {e[q]['rms_band']:.4f}"
                             for q in ("T", "R") + (("A_ito",) if "A_ito" in e else ("A_rt",)) if q in e))
    c3 = em.get("check_300K_vs_existing_final3_prod")
    if c3:
        L.append(f"* **300 K, 600 fs (this family) vs existing final3/prod (300 fs)** — max|ΔT| {c3['max_abs_dT_1230_1280']:.4f}, max|ΔR| {c3['max_abs_dR_1230_1280']:.4f}, "
                 f"max|ΔA| {c3['max_abs_dA_1230_1280']:.4f} in 1230-1280 nm (rms {c3['rms_dT_1230_1280']:.4f} / {c3['rms_dR_1230_1280']:.4f} / {c3['rms_dA_1230_1280']:.4f}); "
                 f"1−R−T at 1255 nm {c3['A_1255_new_rt']:.4f} vs {c3['A_1255_existing']:.4f}.")
    # 4. feedback
    L.append("\n## 4. Thermal feedback (TTM, τ_ep = 450 fs primary)\n")
    L.append(f"Absorption column driving the TTM: `{fb['absorption_column_used']}`.  ZIP labels found with the ZIP criteria: {fb['strict_labels_found']}.  "
             f"ZIP fallback picks (relaxed rules, NOT used as labels): {fb['zip_fallback_would_pick']}.  Strongest increase: λ = {fb['scan_extremes']['max_dT']['lp']:.0f} nm, ΔT = {fb['scan_extremes']['max_dT']['dT']:+.3f}; "
             f"strongest decrease: λ = {fb['scan_extremes']['min_dT']['lp']:.0f} nm, ΔT = {fb['scan_extremes']['min_dT']['dT']:+.4f}.\n")
    L.append("| curve | λ [nm] | T0 | ΔT (0 → 2.4 nJ) | sat. fraction at 1.6 nJ | logistic E0 [nJ] | r² | ZIP criteria met | peak Te (feedback) | peak Te (fixed cold A) | max abs ΔT_eff vs fixed cold A | first I above the 8000 K table |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for lab, m in fb["selected"].items():
        u = fb["feedback_uses_A_of_Te"][lab]; ab = fb["above_table_first_I_Wcm2"][lab]
        L.append(f"| {lab} | {m['lp']:.0f} | {m['T0']:.3f} | {m['dT']:+.3f} | {m['fsat']:.2f} | {m['E0']:.2f} | {m['r2']:.2f} | {bool(m['criteria_met'])} | {u['Te_pk_max_feedback']:.0f} K | {u['Te_pk_max_fixed_cold_A']:.0f} K | {u['max_abs_dTeff_vs_fixed_cold_A']:.3f} | "
                 + (f"{ab:.1e} W/cm²" if ab else "never") + " |")
    L.append(f"\nFamily table: Te rows {fam['Te_K'].tolist()}, λ {fam['lambda_nm'][0]:.0f}-{fam['lambda_nm'][-1]:.0f} nm / 1 nm.  Conventions: {json.dumps(fb['conventions'])}\n")
    (OUT / "SUMMARY.md").write_text("\n".join(L))
    print("\n".join(L))


if __name__ == "__main__":
    import sys
    main(sys.argv[1] if len(sys.argv) > 1 else "fig3")
