"""Insert the machine-generated tables (outputs/tables/*) into REPORT.md section 12 (idempotent: the section is
regenerated between the markers each time)."""
import json
from pathlib import Path

import numpy as np

import common as cm                       # noqa: F401

TAB = cm.OUT / "tables"
START, END = "<!-- TABLES START -->", "<!-- TABLES END -->"


def main():
    rows = cm.jload(TAB / "candidates.json"); sweep = cm.jload(TAB / "threshold_sweep.json"); cor = cm.jload(TAB / "correlations.json")
    par = cm.jload(TAB / "pareto.json"); dsw = cm.jload(TAB / "definition_sweep.json"); bt = cm.jload(TAB / "certified_Q_vs_buildup.json")
    md = (TAB / "candidates.md").read_text()
    n_des = sum(1 for r in rows if r["kind"] != "reference")
    # threshold sweep summary: survivors for a few representative combinations
    def surv(Tb, Cr, Fm, Ez):
        return next((s for s in sweep if s["T_bg_min"] == Tb and s["C_res_min"] == Cr and s["Ftot_min"] == Fm and s["eta_z_min"] == Ez), None)
    combos = [(0.3, 0.05, 0.02, 0.0), (0.5, 0.05, 0.02, 0.0), (0.5, 0.2, 0.1, 0.5), (0.7, 0.2, 0.1, 0.7), (0.7, 0.3, 0.2, 0.8), (0.9, 0.3, 0.2, 0.8)]
    sl = ["| T_bg_min | C_res_min | F_tot,min | eta_z,min | survivors (designs only) | best dT_int |", "|---|---|---|---|---|---|"]
    for c in combos:
        s = surv(*c)
        if s:
            sl.append(f"| {c[0]} | {c[1]} | {c[2]} | {c[3]} | {s['n_survivors']}: {', '.join(s['survivors'])} | {s['best_dT'] or '-'} |")
    # correlations of interest
    cl = ["| x | y | n | Spearman rho | p |", "|---|---|---|---|---|"]
    for k in ("Q_r__vs__dT_max_pos", "eta_Dz_lamE__vs__dT_max_pos", "eta_Dz_P_lamE__vs__dT_max_pos", "T_bg__vs__dT_max_pos", "gamma_nr_over_gamma_r_est__vs__dT_max_pos",
              "Ftot0_pos__vs__dT_max_pos", "eta_z_pos__vs__dT_max_pos", "Q_r__vs__S_T_pos", "eta_Dz_lamE__vs__S_T_pos", "Q_r__vs__loaded_Q_pos"):
        v = cor.get(k, {})
        x, y = k.split("__vs__")
        cl.append(f"| {x} | {y} | {v.get('n')} | {v.get('spearman') if v.get('spearman') is None else round(v['spearman'], 2)} | {v.get('spearman_p') if v.get('spearman_p') is None else round(v['spearman_p'], 3)} |")
    # definition sweep: T_bg spread per candidate
    dl = ["| tag | T_bg (k=1, D=30) | (k=3, D=50, default) | (k=5, D=80) | undefined for |", "|---|---|---|---|---|"]
    for tag, d in dsw.items():
        und = [k for k, v in d.items() if not v["defined"]]
        f = lambda k: ("-" if d[k]["T_bg"] is None else f"{d[k]['T_bg']:.2f}")
        dl.append(f"| {tag} | {f('k1_D30')} | {f('k3_D50')} | {f('k5_D80')} | {len(und)}/{len(d)} |")
    bc = bt["correlations"]
    body = f'''
## 12. Tables (generated by `select_pareto.py`; sorted by the interior positive dT)

{n_des} campaign / baseline designs + {len(rows) - n_des} references.  `T_bg`, `C_res_ext`: parent (no ITO); `T0_loaded_median`:
median cold loaded T over the safe window; `lam_op_int`, `dT_int`, `S_T_int`, `T0_int`, `Ftot0_int`, `eta_z_int`: the interior
operating point (argmax dT with lambda >= lambda_R + 20 nm and <= 1395 nm); `lam_op_pos`, `dT_max_pos`: the unguarded argmax
(flagged `at_window_edge_pos` when it sits on the safe-window edge); `gamma_nr_over_gamma_r_est`: parent-only first-order
estimate; `loaded_Q_pos`: exact loaded AAA pole nearest lambda_op; `unresolved_pos`: [9,9] -> [11,11] change of dT above
max(0.02, 20 %); `dominated_activation_axes`: dominated on (dT_int, T_bg, C_res_ext, F_tot, eta_z, T0_loaded_median, Q_r, eta_Dz).

{md}
Non-dominated set: {', '.join(par['non_dominated'])}.

### 12.1 Threshold sweep (`threshold_sweep.json`, {len(sweep)} combinations; survivors need dT_int > 0)

{chr(10).join(sl)}

### 12.2 Correlations across the {n_des} designs (`correlations.json`)

{chr(10).join(cl)}

Certified parents only (`certified_Q_vs_buildup.json`): Spearman of log Q_r with U_mid(lambda_r) = {bc['all_certified_with_pole']['U_mid_lamr']['spearman_vs_logQ']:+.2f},
with eta_Dz(lambda_r) = {bc['all_certified_with_pole']['eta_Dz_lamr']['spearman_vs_logQ']:+.2f} (n = {bc['all_certified_with_pole']['n']}); aligned subset (|detuning| < 1.5 linewidths, n = {bc['aligned_abs_detuning_lt_1p5_lw']['n']}):
U_mid {bc['aligned_abs_detuning_lt_1p5_lw']['U_mid_lamr']['spearman_vs_logQ']:+.2f}, eta_Dz {bc['aligned_abs_detuning_lt_1p5_lw']['eta_Dz_lamr']['spearman_vs_logQ']:+.2f}.

### 12.3 Sensitivity of T_bg to its definition (`definition_sweep.json`; k = linewidths excluded per pole, D = ENZ half-window in nm)

{chr(10).join(dl)}
'''
    p = cm.HERE / "REPORT.md"; s = p.read_text()
    if START in s and END in s:
        s = s[:s.index(START)] + START + body + END + s[s.index(END) + len(END):]
    else:
        s = s.replace("RESULTS_TABLE_PLACEHOLDER", START + body + END)
    p.write_text(s); print("REPORT.md section 12 regenerated")


if __name__ == "__main__":
    main()
